sudo: false
language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.13.6
env:
  global:
    - CC_TEST_REPORTER_ID=1ce5201f57b288a53e33ae8768ed7700578dffce593c814deceb0051bc208d24
    - COVERAGE=true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
