sudo: false
language: ruby
rvm:
  - 2.5.3
services:
  - mysql
before_install:
  - gem install bundler -v 1.13.6
  - mysql -e 'CREATE DATABASE IF NOT EXISTS next_train_test;'
env:
  global:
    - DATABASE_USER="travis"
    - DATABASE_PASSWORD=""
    - MAILER_HOST="next-train-example.com"
    - ADMIN_EMAIL="someone@gmail.com"
    - CC_TEST_REPORTER_ID=1ce5201f57b288a53e33ae8768ed7700578dffce593c814deceb0051bc208d24
    - COVERAGE=true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
